export enum ErrorCode {
  // Base
  UNKNOWN = 'UNKNOWN',

  // Auth
  INVALID_AUTHORIZATION = 'INVALID_AUTHORIZATION',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  SUSPENDED_TOO_MANY_ATTEMPTS = 'SUSPENDED_TOO_MANY_ATTEMPTS',
  INVALID_USERNAME_OR_PASSWORD = 'INVALID_USERNAME_OR_PASSWORD',
  MISSING_AUTHORIZATION = 'MISSING_AUTHORIZATION',
  INVALID_PIN = 'INVALID_PIN',
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
  OLD_PASSWORD_NOT_CORRECT = 'OLD_PASSWORD_NOT_CORRECT',
}
